# Generated by Django 4.0.3 on 2022-05-27 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(db_index=True, max_length=500, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(db_index=True, max_length=500, verbose_name='token'),
        ),
    ]
